label_studio.url: http://51.250.54.76:8080

yc.object_storage:
  region_name: ru-central1-b
  endpoint: "https://storage.yandexcloud.net"
  folder: b1g4t4cvnf6vlitutlmc

projects:
  - details:
      # parameters matches the Label Studio SDK `project.create` method
      # see full list here https://labelstud.io/api#tag/Projects
      title: "Image Classification"
      description: "test project"
      expert_instruction: "Select the category that best describes the image"
      show_instruction: true
      show_annotation_history: true
      reveal_preannotations_interactively: false
      show_collab_predictions: true
      color: "#808000"
      label_config: |
        <View style="display:flex;align-items:start;gap:8px;flex-direction:row-reverse">
          <Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true"/>
          <RectangleLabels name="label" toName="image" strokeWidth="2" showInline="false">
            <!-- Tops -->
            <Label value="page-header" background="LightSkyBlue" hotkey="1"/>
            <!-- Body -->
            <Label value="section-header" background="Olive" hotkey="2"/>
            <Label value="text" background="PaleGreen" hotkey="3"/>
            <Label value="title" background="DarkGreen" hotkey="4"/>
            <Label value="picture" background="MediumPurple" hotkey="5"/>
            <Label value="caption" background="MediumPurple" hotkey="6"/>
            <Label value="formula" background="Gold" hotkey="7"/>
            <Label value="table" background="DarkKhaki" hotkey="8"/>
            <Label value="list-item" background="DarkSeaGreen" hotkey="9"/>

            <!-- Bottom -->
            <Label value="footnote" background="Tan" hotkey="0"/>
            <Label value="page-footer" background="Peru" hotkey="-"/>
          </RectangleLabels>
        </View>
    storages:
      # `object_storage_params matches` the YC `BucketServiceStub.Create` method
      # see full list here https://yandex.cloud/en/docs/storage/api-ref/grpc/bucket_service#Create
      # `ls_storage_params` matches the Label Studio's `import_storage` and `export_storage` CREATE methods
      # see full list here https://api.labelstud.io/api-reference/api-reference/import-storage/s-3/create
      - type: "import"
        title: "tasks-and-images"
        object_storage_params:
        ls_storage_params:
          regex_filter: ".*.json"
          presign: true
      - type: "export"
        title: "annotations"
        object_storage_params:
        ls_storage_params:
          can_delete_objects: true





