label_studio.url: http://51.250.54.76:8080

yc.object_storage:
  region_name: ru-central1-b
  endpoint: "https://storage.yandexcloud.net"
  folder: b1g4t4cvnf6vlitutlmc

projects:
  - details:
      # parameters matches the Label Studio SDK `project.create` method
      # see full list here https://labelstud.io/api#tag/Projects
      title: "LOW DPI - Document Layout Analysis"
      description: |
        This project labels and analyzes the layout structures of Tatar books, identifying elements like headers, footers, paragraphs, images, tables, and footnotes to enhance the preservation and accessibility of Tatar literature.
      expert_instruction: |
        Expert Instructions for Document Layout Analysis
        
        In this project, you will label various layout elements on the pages of Tatar books. Below are the types of layouts you will encounter and instructions on how to identify and define them:
        
        1. Text (Regular paragraphs):
        Identify blocks of continuous text.
        Label each paragraph individually, even if they are part of a larger section.
        
        2. Picture:
        Recognize any graphic or photograph within the document.
        Draw a bounding box around the entire graphic element and label it as "Picture."
        
        3. Caption:
        Look for special text that introduces or explains a picture or table.
        This text is usually outside the main text flow and is directly associated with an image or table.
        Label this text as "Caption."
        
        4. Section-header:
        Identify any kind of heading within the text, excluding the overall document title.
        These are typically in a larger or bold font and signify the beginning of a new section.
        Label these headings as "Section-header."
        
        5. Footnote:
        Find small text at the bottom of a page, typically associated with a number or symbol in the main text.
        Footnotes provide additional information or references and are often in a smaller font.
        Label this text as "Footnote."
        
        6. Formula:
        Recognize any mathematical equation that is presented on its own line.
        These are usually distinct from the main text and may involve special characters or formatting.
        Label these equations as "Formula."
        
        7. Table:
        Identify material arranged in a grid format with rows and columns, often separated by lines.
        Each table usually contains headings and cells with text or numbers.
        Label the entire structure as "Table."
        
        8. List-item:
        Look for elements of a list, where each item is presented in a hanging format.
        From the second line onwards, the paragraph is indented more than the first line.
        Label each item in the list individually as "List-item."
        
        9. Page-header:
        Recognize repeating elements like page numbers or titles at the top of the page, outside of the main text flow.
        These are typically found in the same position on every page.
        Label these elements as "Page-header."
        
        10. Page-footer:
        Identify repeating elements like page numbers or footers at the bottom of the page, outside of the main text flow.
        These elements are also found in the same position on every page.
        Label these elements as "Page-footer."
        
        11. Title:
        Find the overall title of the document, which is usually located on the first page.
        This title is typically in a larger font and may span multiple lines.
        Label this text as "Title."
        
        Use these guidelines to accurately label the elements within the document pages. Your detailed annotations will significantly contribute to the preservation and accessibility of Tatar literature.
      show_instruction: false
      show_annotation_history: true
      reveal_preannotations_interactively: false
      show_collab_predictions: true
      color: "#008000"
      label_config: |
        <View style="display:flex;align-items:start;gap:8px;flex-direction:row-reverse">
          <Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true" crosshair="true"/>
          <RectangleLabels name="label" toName="image" strokeWidth="2" showInline="false">
            <Label value="page-header" background="LightSkyBlue" hotkey="1"/>
            <Label value="section-header" background="Olive" hotkey="2"/>
            <Label value="text" background="PaleGreen" hotkey="3"/>
            <Label value="title" background="DarkGreen" hotkey="4"/>
            <Label value="poetry" background="MediumSeaGreen" hotkey="5"/>
            <Label value="footnote" background="Tan" hotkey="6"/>
            <Label value="page-footer" background="Peru" hotkey="7"/>
            <Label value="picture" background="MediumPurple" hotkey="8"/>
            <Label value="caption" background="MediumPurple" hotkey="9"/>
            <Label value="formula" background="Gold" hotkey="0"/>
            <Label value="table" background="DarkKhaki" hotkey="-"/>
            <Label value="list-item" background="DarkSeaGreen" hotkey="="/>
          </RectangleLabels>
        </View>
    storages:
      # `object_storage_params matches` the YC `BucketServiceStub.Create` method
      # see full list here https://yandex.cloud/en/docs/storage/api-ref/grpc/bucket_service#Create
      # `ls_storage_params` matches the Label Studio's `import_storage` and `export_storage` CREATE methods
      # see full list here https://api.labelstud.io/api-reference/api-reference/import-storage/s-3/create
      - type: "import"
        title: "import"
        object_storage_params:
        ls_storage_params:
          regex_filter: ".*.json"
          presign: true
          presign_ttl: 128
          recursive_scan: true
          use_blob_urls: false
      - type: "export"
        title: "export"
        object_storage_params:
        ls_storage_params:
          can_delete_objects: true





