project:
  model_version: yolov10b
  details:
    title: "Документ урнаштыру тәртибе | Document Layout"
    description: |
      Документ компонентларының тамга һәм чикләр фаразын тикшерү | Check prediction of labels and bounds of document layouts
    color: "#008000"
    # same as in the template.yaml but without the title label
    label_config: |
      <View style="display:flex;align-items:start;gap:8px;flex-direction:row-reverse">
        <Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true" crosshair="true"/>
        <RectangleLabels name="label" toName="image" strokeWidth="2" showInline="false">
          <Label value="Бит өсбашы / Заголовок страницы" alias="page-header" background="LightSkyBlue" hotkey="1" showAlias="true"/>
          <Label value="Бүлек башы / Заголовок раздела" alias="section-header" background="Olive" hotkey="2" showAlias="true"/>
          <Label value="Текст" alias="text" background="PaleGreen" hotkey="3" showAlias="true"/>
          <Label value="Шигырь / Стихи" alias="poetry" background="MediumSeaGreen" hotkey="5" showAlias="true"/>
          <Label value="Асъязма / Сноска" alias="footnote" background="Tan" hotkey="6" showAlias="true"/>
          <Label value="Бит асъягы / Нижний колонтитул" alias="page-footer" background="Peru" hotkey="7" showAlias="true"/>
          <Label value="Рәсем / Изображение" alias="picture" background="MediumPurple" hotkey="8" showAlias="true"/>
          <Label value="Рәсем тасвиры / Подпись к изобр." alias="caption" background="MediumPurple" hotkey="9" showAlias="true"/>
          <Label value="Математик формула / Матем. формула" alias="formula" background="Gold" hotkey="0" showAlias="true"/>
          <Label value="Җәдвал / Таблица" alias="table" background="DarkKhaki" hotkey="-" showAlias="true"/>
          <Label value="Исемлек тармагы / Элемент списка" alias="list-item" background="DarkSeaGreen" hotkey="=" showAlias="true"/>
        </RectangleLabels>
      </View>
  storages:
    # `ls_storage_params` matches the Label Studio's `import_storage` and `export_storage` CREATE methods
    # see full list here https://api.labelstud.io/api-reference/api-reference/import-storage/s-3/create
    - title: "label-studio-import-tasks"
      ty: "import"
      ls_storage_params:
        regex_filter: ".*.json"
        presign: true
        presign_ttl: 128
        recursive_scan: true
        use_blob_urls: false
    - title: "label-studio-import-images"
      ty: "import"
      ls_storage_params:
        regex_filter: ".*.png"
        presign: true
        presign_ttl: 128
        recursive_scan: true
        use_blob_urls: false
    - title: "label-studio-export-annotations"
      ty: "export"
      ls_storage_params:
        can_delete_objects: false