project:
  model_version: yolov10b
  details:
    title: "Документ урнаштыру тәртибе | Document Layout"
    description: |
      Документ компонентларының тамга һәм чикләр фаразын тикшерү | Check prediction of labels and bounds of document layouts
    color: "#008000"
    # same as in the template.yaml but without the title label
    label_config: |
      <View style="display:flex;align-items:start;gap:8px;flex-direction:row-reverse">
        <Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true" crosshair="true"/>
        <RectangleLabels name="label" toName="image" strokeWidth="2" showInline="false">
          <Label value="Бит өсбашы | Заголовок страницы |" alias="page-header" background="#4169E1" hotkey="1" showAlias="true"/>
          <Label value="Текст | Текст |" alias="text" background="LightGreen" hotkey="2" showAlias="true"/>
          <Label value="Бүлек башы | Заголовок раздела |" alias="section-header" background="DarkKhaki" hotkey="3" showAlias="true"/>
          <Label value="Асъязма | Сноска |" alias="footnote" background="#2F4F4F" hotkey="4" showAlias="true"/>
          <Label value="Шигырь | Стихи |" alias="poetry" background="#800000" hotkey="5" showAlias="true"/>
          <Label value="Бит асъягы | Нижний колонтитул |" alias="page-footer" background="Coral" hotkey="6" showAlias="true"/>
          <Label value="Рәсем | Изображение |" alias="picture" background="#008080" hotkey="7" showAlias="true"/>
          <Label value="Җәдвал | Таблица |" alias="table" background="#DAA520" hotkey="8" showAlias="true"/>
          <Label value="Рәсем/җәдвал тасвиры | Подпись к изобр./табл. |" alias="caption" background="#8B4513" hotkey="9" showAlias="true"/>
          <Label value="Формула | Формула |" alias="formula" background="grey" hotkey="0" showAlias="true"/>
          <Label value="Исемлек тармагы | Элемент списка |" alias="list-item" background="#BA55D3" hotkey="-" showAlias="true"/>
        </RectangleLabels>
      </View>
  storages:
    # `ls_storage_params` matches the Label Studio's `import_storage` and `export_storage` CREATE methods
    # see full list here https://api.labelstud.io/api-reference/api-reference/import-storage/s-3/create
    - title: "label-studio-import-tasks"
      ty: "import"
      ls_storage_params:
        regex_filter: ".*.json"
        presign: true
        presign_ttl: 128
        recursive_scan: true
        use_blob_urls: false
    - title: "label-studio-import-images"
      ty: "import"
      ls_storage_params:
        regex_filter: ".*.png"
        presign: true
        presign_ttl: 128
        recursive_scan: true
        use_blob_urls: false
    - title: "label-studio-export-annotations"
      ty: "export"
      ls_storage_params:
        can_delete_objects: false