project:
  model_version: yolov10b
  details:
    title: "Документның баш битен тамгалау | Document Layout"
    description: |
      Бу проектта документның беренче бите генә тамгалана һәм монда гына башисем(title) әгъзасы бар
    color: "#5234EB"
  storages:
    # `ls_storage_params` matches the Label Studio's `import_storage` and `export_storage` CREATE methods
    # see full list here https://api.labelstud.io/api-reference/api-reference/import-storage/s-3/create
    - title: "label-studio-import-title-tasks"
      ty: "import"
      ls_storage_params:
        regex_filter: ".*.json"
        presign: true
        presign_ttl: 128
        recursive_scan: true
        use_blob_urls: false
    - title: "label-studio-import-images"
      ty: "import"
      ls_storage_params:
        regex_filter: ".*.png"
        presign: true
        presign_ttl: 128
        recursive_scan: true
        use_blob_urls: false
    - title: "label-studio-export-annotations"
      ty: "export"
      ls_storage_params:
        can_delete_objects: false